name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
    - name: Test automatically
      run: |
        VSTest.Console.exe BiosTicketSystemTests.dll
