name: .NET

on:
  push:
    branches: [ automated-testing ]
  pull_request:
    branches: [ automated-testing ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
    - name: Test automatically
      run: |
        VSTest.Console.exe BiosTicketSystem\BiosTicketSystemTests.dll
